/*

 CIRCLE_SMALL_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __circle_small_tiles_h_INCLUDE
#define __circle_small_tiles_h_INCLUDE

/* Bank of tiles. */
#define circle_small_tilesBank 0

/* Super Gameboy palette 0 */
#define circle_small_tilesSGBPal0c0 0
#define circle_small_tilesSGBPal0c1 15648
#define circle_small_tilesSGBPal0c2 16082
#define circle_small_tilesSGBPal0c3 15

/* Super Gameboy palette 1 */
#define circle_small_tilesSGBPal1c0 6076
#define circle_small_tilesSGBPal1c1 8935
#define circle_small_tilesSGBPal1c2 6596
#define circle_small_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define circle_small_tilesSGBPal2c0 6076
#define circle_small_tilesSGBPal2c1 8935
#define circle_small_tilesSGBPal2c2 6596
#define circle_small_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define circle_small_tilesSGBPal3c0 6076
#define circle_small_tilesSGBPal3c1 8935
#define circle_small_tilesSGBPal3c2 6596
#define circle_small_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define circle_small_tilesCGBPal0c0 5383
#define circle_small_tilesCGBPal0c1 16085
#define circle_small_tilesCGBPal0c2 22396
#define circle_small_tilesCGBPal0c3 31743

/* Gameboy Color palette 1 */
#define circle_small_tilesCGBPal1c0 9936
#define circle_small_tilesCGBPal1c1 11096
#define circle_small_tilesCGBPal1c2 0
#define circle_small_tilesCGBPal1c3 23119

/* Gameboy Color palette 2 */
#define circle_small_tilesCGBPal2c0 495
#define circle_small_tilesCGBPal2c1 32160
#define circle_small_tilesCGBPal2c2 27403
#define circle_small_tilesCGBPal2c3 10

/* Gameboy Color palette 3 */
#define circle_small_tilesCGBPal3c0 19229
#define circle_small_tilesCGBPal3c1 15862
#define circle_small_tilesCGBPal3c2 10240
#define circle_small_tilesCGBPal3c3 10439

/* Gameboy Color palette 4 */
#define circle_small_tilesCGBPal4c0 2
#define circle_small_tilesCGBPal4c1 7488
#define circle_small_tilesCGBPal4c2 32070
#define circle_small_tilesCGBPal4c3 15

/* Gameboy Color palette 5 */
#define circle_small_tilesCGBPal5c0 12268
#define circle_small_tilesCGBPal5c1 11096
#define circle_small_tilesCGBPal5c2 16384
#define circle_small_tilesCGBPal5c3 24886

/* Gameboy Color palette 6 */
#define circle_small_tilesCGBPal6c0 346
#define circle_small_tilesCGBPal6c1 0
#define circle_small_tilesCGBPal6c2 0
#define circle_small_tilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define circle_small_tilesCGBPal7c0 13094
#define circle_small_tilesCGBPal7c1 11096
#define circle_small_tilesCGBPal7c2 0
#define circle_small_tilesCGBPal7c3 0
/* Start of tile array. */
extern const unsigned char circle_small_tiles[];

#endif

/* End of CIRCLE_SMALL_TILES.H */
