/*

 CIRCLE_LARGE_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __circle_large_tiles_h_INCLUDE
#define __circle_large_tiles_h_INCLUDE

/* Bank of tiles. */
#define circle_large_tilesBank 0

/* Super Gameboy palette 0 */
#define circle_large_tilesSGBPal0c0 0
#define circle_large_tilesSGBPal0c1 19744
#define circle_large_tilesSGBPal0c2 26640
#define circle_large_tilesSGBPal0c3 15

/* Super Gameboy palette 1 */
#define circle_large_tilesSGBPal1c0 6076
#define circle_large_tilesSGBPal1c1 8935
#define circle_large_tilesSGBPal1c2 6596
#define circle_large_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define circle_large_tilesSGBPal2c0 6076
#define circle_large_tilesSGBPal2c1 8935
#define circle_large_tilesSGBPal2c2 6596
#define circle_large_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define circle_large_tilesSGBPal3c0 6076
#define circle_large_tilesSGBPal3c1 8935
#define circle_large_tilesSGBPal3c2 6596
#define circle_large_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define circle_large_tilesCGBPal0c0 5383
#define circle_large_tilesCGBPal0c1 16085
#define circle_large_tilesCGBPal0c2 22396
#define circle_large_tilesCGBPal0c3 31743

/* Gameboy Color palette 1 */
#define circle_large_tilesCGBPal1c0 18960
#define circle_large_tilesCGBPal1c1 10503
#define circle_large_tilesCGBPal1c2 0
#define circle_large_tilesCGBPal1c3 531

/* Gameboy Color palette 2 */
#define circle_large_tilesCGBPal2c0 506
#define circle_large_tilesCGBPal2c1 14752
#define circle_large_tilesCGBPal2c2 8436
#define circle_large_tilesCGBPal2c3 10

/* Gameboy Color palette 3 */
#define circle_large_tilesCGBPal3c0 17309
#define circle_large_tilesCGBPal3c1 16192
#define circle_large_tilesCGBPal3c2 4096
#define circle_large_tilesCGBPal3c3 22549

/* Gameboy Color palette 4 */
#define circle_large_tilesCGBPal4c0 2
#define circle_large_tilesCGBPal4c1 21632
#define circle_large_tilesCGBPal4c2 32448
#define circle_large_tilesCGBPal4c3 15

/* Gameboy Color palette 5 */
#define circle_large_tilesCGBPal5c0 20940
#define circle_large_tilesCGBPal5c1 10503
#define circle_large_tilesCGBPal5c2 16384
#define circle_large_tilesCGBPal5c3 7760

/* Gameboy Color palette 6 */
#define circle_large_tilesCGBPal6c0 328
#define circle_large_tilesCGBPal6c1 0
#define circle_large_tilesCGBPal6c2 0
#define circle_large_tilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define circle_large_tilesCGBPal7c0 21566
#define circle_large_tilesCGBPal7c1 10503
#define circle_large_tilesCGBPal7c2 0
#define circle_large_tilesCGBPal7c3 0
/* Start of tile array. */
extern const unsigned char circle_large_tiles[];

#endif

/* End of CIRCLE_LARGE_TILES.H */
