/*

 SPRITE_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 7

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define sprite_tilesBank 0

/* Super Gameboy palette 0 */
#define sprite_tilesSGBPal0c0 0
#define sprite_tilesSGBPal0c1 0
#define sprite_tilesSGBPal0c2 10240
#define sprite_tilesSGBPal0c3 979

/* Super Gameboy palette 1 */
#define sprite_tilesSGBPal1c0 6076
#define sprite_tilesSGBPal1c1 8935
#define sprite_tilesSGBPal1c2 6596
#define sprite_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define sprite_tilesSGBPal2c0 6076
#define sprite_tilesSGBPal2c1 8935
#define sprite_tilesSGBPal2c2 6596
#define sprite_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define sprite_tilesSGBPal3c0 6076
#define sprite_tilesSGBPal3c1 8935
#define sprite_tilesSGBPal3c2 6596
#define sprite_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define sprite_tilesCGBPal0c0 10661
#define sprite_tilesCGBPal0c1 26588
#define sprite_tilesCGBPal0c2 14096
#define sprite_tilesCGBPal0c3 2112

/* Gameboy Color palette 1 */
#define sprite_tilesCGBPal1c0 6076
#define sprite_tilesCGBPal1c1 8935
#define sprite_tilesCGBPal1c2 6596
#define sprite_tilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define sprite_tilesCGBPal2c0 6076
#define sprite_tilesCGBPal2c1 8935
#define sprite_tilesCGBPal2c2 6596
#define sprite_tilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define sprite_tilesCGBPal3c0 6076
#define sprite_tilesCGBPal3c1 8935
#define sprite_tilesCGBPal3c2 6596
#define sprite_tilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define sprite_tilesCGBPal4c0 6076
#define sprite_tilesCGBPal4c1 8935
#define sprite_tilesCGBPal4c2 6596
#define sprite_tilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define sprite_tilesCGBPal5c0 6076
#define sprite_tilesCGBPal5c1 8935
#define sprite_tilesCGBPal5c2 6596
#define sprite_tilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define sprite_tilesCGBPal6c0 6076
#define sprite_tilesCGBPal6c1 8935
#define sprite_tilesCGBPal6c2 6596
#define sprite_tilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define sprite_tilesCGBPal7c0 6076
#define sprite_tilesCGBPal7c1 8935
#define sprite_tilesCGBPal7c2 6596
#define sprite_tilesCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char sprite_tiles[];

/* End of SPRITE_TILES.H */
