
# Platform specific flags for compiling (only populate if they're both present)
ifneq ($(strip $(PORT)),)
ifneq ($(strip $(PLAT)),)
CFLAGS += -m$(PORT):$(PLAT)
LCCFLAGS += -m$(PORT):$(PLAT)
endif
endif

# Called by the individual targets below to build a ROM
build-target: $(BINS)

clean-target:
	rm -rf $(OBJDIR)
	rm -rf $(BINDIR)

gb-clean:
	${MAKE} clean-target PLAT=gb EXT=gb
gb:
	${MAKE} build-target PORT=sm83 PLAT=gb EXT=gb PLAT_SRC_NAME=gb


gbc-clean:
	${MAKE} clean-target PLAT=gbc EXT=gbc
gbc:
	${MAKE} build-target PORT=sm83 PLAT=gb EXT=gbc PLAT_SRC_NAME=gb


pocket-clean:
	${MAKE} clean-target PLAT=pocket EXT=pocket
pocket:
	${MAKE} build-target PORT=sm83 PLAT=ap EXT=pocket PLAT_SRC_NAME=gb  # Note src dir name same as gb


megaduck-clean:
	${MAKE} clean-target PLAT=duck EXT=duck
megaduck:
	${MAKE} build-target PORT=sm83 PLAT=duck EXT=duck PLAT_SRC_NAME=duck


sms-clean:
	${MAKE} clean-target EXT=sms
sms:
	${MAKE} build-target PORT=z80 PLAT=sms EXT=sms


gg-clean:
	${MAKE} clean-target EXT=gg
gg:
	${MAKE} build-target PORT=z80 PLAT=gg EXT=gg

